import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const areal = localFont({
  src: "../../public/font/ABCArealVariable.woff2",
  variable: "--font-areal",
});

const arealMono = localFont({
  src: "../../public/font/ABCArealMonoVariable.woff2",
  variable: "--font-areal-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${areal.variable} ${arealMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col my-8 mx-16">{children}</body>
    </html>
  );
}
